### ISSUE TITLE
Explain "Tribalism" 

### ISSUE THREAD

**Issue by timmwille** [gibertgibs/ACt-Against-TRIBALISM#1]
For me I thought Tribalism is a rather cultural thing, but I guess it can be also a more dangerous aspect. maybe clarify how it differs regarding cultural groups and influences?

**Comment by gibertgibs** [comment]
Tribalism in the Webster Dictionary has been defined as " Behaviour, attitude that stem from strong loyalty to one's own tribe or other social groups"
Which then makes it clear that if one is in that shoe of being tribalistic, He/she takes the rest of the other tribes to be like a label. And this is what I call tribalism, it has nothing to culture, I my own understanding, tribalism it is what we teach to the people. I can quote " I am not black, I was taught be black" and " And you are not white, you were taught to be a white" This is what I call a label, but then when I relate it back to tribalism, "I was not born having a negative attitude towards the Madi, and you were never born doing the same, But you were taught to do so.....This is what I call tribalism, to do things that favour, my own tribe not seeing the other side of the story. I see no difference between racism and tribalism, because they are moreless equal.

**Comment by gibertgibs** [comment]
Tribalism is way more dangerous than the cultural influence, because year after year, numerous citizens tend to face violence due to their ethnicity, tribe or social group.
An example I can put is a Madi from Uganda being so profound of his tribe or ethnicity in a way he or she doesn't want like the weakness of his tribe or ethnic group to be pointed....After doing this, he or she can tend to be like real horror.
So tribalism can run International if not well handled, He who is tribalistic, sees himself through the lens of his tribes and ethnicity, and always carries a banner of his tribe's affiliation in heart.

**Comment by timmwille** [comment]
@gibertgibs I just see this now, thx for explaining this in such detail. This is serious, so a lot of this reminds me of people fighting about views and personal concepts without listening to the other perspective as equally valuable and take peace and respectful treatment as foundation.
